services:
  - type: web
    name: mesada-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask --app run.py db upgrade
    startCommand: gunicorn run:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
